import {Player} from "./models/Player";

export const playersMock: Player[] = [
    {
        name: "Vonki",
        id_discord: '1',
        id: '1',
        elo: 1000,
        role: "TOP",
        ready: true,
    },
    {
        name: "Chief",
        id_discord: '3',
        id: '3',
        elo: 1000,
        role: "MID",
        ready: true,
    },
    {
        name: "Rayffen",
        id_discord: '4',
        id: '4',
        elo: 1000,
        role: "BOT",
        ready: true,
    },
    {
        name: "Lyonz",
        id_discord: '5',
        id: '5',
        elo: 1000,
        role: "SUPP",
        ready: true,
    },
    {
        name: "Lukenzo",
        id_discord: '6',
        id: '6',
        elo: 1000,
        role: "TOP",
        ready: true,
    },
    {
        name: "AxlBg",
        id_discord: '7',
        id: '7',
        elo: 1000,
        role: "JG",
        ready: true,
    },
    {
        name: "Joelito",
        id_discord: '8',
        id: '8',
        elo: 1000,
        role: "MID",
        ready: true,
    },
    {
        name: "Kc",
        id_discord: '9',
        id: '9',
        elo: 1000,
        role: "BOT",
        ready: true,
    },
    {
        name: "Tomate",
        id_discord: '10',
        id: '10',
        elo: 1000,
        role: "SUPP",
        ready: true,
    },
];